### ISSUE TITLE
How to perform the same execution the plugin does but with the console

### ISSUE THREAD

**Issue by lhidalgoblanco-technisys** [tomcatplugin/tomcatplugin#15]
So this is the deal, I am using the net.sf.eclipse.tomcat.updatesite-2016-04-19 plugin (I know it's an older version but help me out) and I'm running an application that I just recently migrated to tomcat 8.5. What happens is that when I run the application with the plugin it does so perfectly but when I build the .war, put it in webapps and run the "./catalina.sh run" the app doesn't start up. I noticed that the plugin loads a lot of jars from .m2 and does many other things that somehow makes it possible for the application to actually run and that's why I need to know exactly how the plugin executes the webapps, so I can perform the same process using a command line and not eclipse directly. 

Please help. 
Thank you.

**Comment by markuskeunecke** [comment]
Basically the Plugin launches the configured Tomcat installation. If your webapp is properly configured you should be able to deploy it into another Tomcat and launch it from there. From your question it is not clear to me what "does not start up" means exactly? Logs? Error messages?

**Comment by markuskeunecke** [comment]
Seems to be obsolete.
