### ISSUE TITLE
cannot un-check use SMART! maven classpath

### ISSUE THREAD

**Issue by pstanton** [tomcatplugin/tomcatplugin#17]
In project properties -> DevLoader classpath, there if i uncheck "Use SMART! maven classpath". If I uncheck it and apply, it is checked again when i return.

**Comment by jochenw** [comment]
Reproducable with Eclipse 4.18M1, and 9.1.5. I will look into this.

**Comment by jochenw** [comment]
The problem seems to be in net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatProjectWebclasspathPropertyPage.java:

                        List newSelection = cpList.getCheckedElements();
 
                        try {
        -                       if (mavenClassPathCheck.getSelection()) {
        -                               page.getTomcatProject().setMavenClasspath(true);
        -                       }
       +                       page.getTomcatProject().setMavenClasspath(mavenClassPathCheck.getSelection());
                               if (webClassPathCheck.getSelection()) {
                                        page.getTomcatProject().setWebClassPathEntries(new WebClassPathEntries(newSelection));
                        } else {

@markuskeunecke As the fix is quite simple: Could you spare me the trouble of going throw a fork/commit/PR iteration, and accept the fix, like this?

**Comment by markuskeunecke** [comment]
Thank you @jochenw for your fix. We will release this with a future release.
