### ISSUE TITLE
How to add tomcat button to star, stop and restart tomcat server in eclipse , i have downloaded eclipse plugin for tomcat

### ISSUE THREAD

**Issue by Ravi069** [tomcatplugin/tomcatplugin#18]
How to add tomcat button to star, stop and restart tomcat server in eclipse

**Comment by jochenw** [comment]
If those buttons are absent, then (most likely) the plugin is either not really installed, or deactivated, or whatever else. Open "Help/About Eclipse IDE", and then click on "Installation Details". You should see an entry "Eclipse Tomcat Management Feature".

**Comment by markuskeunecke** [comment]
Seems to be outdated.
