### ISSUE TITLE
Add support for Tomcat 10

### ISSUE THREAD

**Issue by ConiKost** [tomcatplugin/tomcatplugin#24]
Since Tomcat 10 started to release its first milestone builds, we should support Tomcat 10 in future.

**Comment by nhnb** [comment]
A quick question: Are there any issues with Tomcat 10 beside the missing option in the preferences dialog?

**Comment by markuskeunecke** [comment]
If the directory structure did not change you can test by choosing Tomcat 9 and let the configuration point to a version 10 Tomcat.

**Comment by ConiKost** [comment]
Looks good. I've just give a try and started ```Apache Tomcat/10.0.0-M8```. So no new entry needed. Maybe it's a good idea then to rename ```Tomcat 9```to ```Tomcat 9+```or ```Tomcat 9/10```?

**Comment by markuskeunecke** [comment]
That's more of a usability thing, I think I'd prefer renaming the option to Tomcat 9+ in the UI. Any other opinions on that?
