### ISSUE TITLE
Wont work on Unbuntu

### ISSUE THREAD

**Issue by stefanlechner** [tomcatplugin/tomcatplugin#29]
I cant get this plugin working on a ubuntu 18.04.5 LTS
$CATALINA_HOME and $CATALINA_BASE are separated.
conf is located in $CATALINA_BASE
There are two JDK Installations 8 and 11. Tomcat is required to use 8.
I always got "Impossible to start Tomcat"

Both directories are set correctly, btw. conf should be located in $CATALINA_BASE not ..HOME
Symlinked to CATALINA_HOME to go around this problem 
All access rights are correct.
Assumed to not be required to set CLASSPATH for Standalone startup, however with or without adding classpath it will not start.

**Comment by jochenw** [comment]
@stefanlechner Could you please help me to reproduce your issue?

1. What version of Tomcat are you using?
2. Where are your variables CATALINA_HOME, and CATALINA_BASE pointing to?
3. Which directories/files are in $CATALINA_HOME, and $CATALINA_BASE, respectively?
4. Can I assume, that these environment variables are set, when Eclipse is launched? Or, in other words: Are they present in Eclipse? (See Help/About Eclipse/Installation Details/Copy to Clipboard, and find the text "System environment variables" in the copied text.)

**Comment by jochenw** [comment]
No response in close to two years. @markuskeunecke: I suggest to close this issue as "Invalid".
