### ISSUE TITLE
Plugin does not add all projects to classpath

### ISSUE THREAD

**Issue by ghost** [tomcatplugin/tomcatplugin#30]
Hi,

In the latest version of the plugin (version 9.1.5) if there are two or more projects selected in the "**Add Java projects to Tomcat classpath**" list of **Tomcat** >> **Advanced** settings, the generated classpath only has reference to the latest project from the list and its dependencies. The references to the other projects from the list are not present in the classpath generated.

A version of the plugin that was working fine is 9.1.2.

**Comment by ConiKost** [comment]
I guess this can be closed, as 9.1.6 has been released and contains the fix?

**Comment by ConiKost** [comment]
@markuskeunecke ^^

**Comment by markuskeunecke** [comment]
I guess so. ;)
