### ISSUE TITLE
How to export the .war?

### ISSUE THREAD

**Issue by PcMant** [tomcatplugin/tomcatplugin#36]
No entiendo nada, ¿por qué no ponen manuales ni guías? Esto es un auténtico lío y dolor de cabeza

**Comment by markuskeunecke** [comment]
I am not sure what you are asking for. But creating a war file is out of scope of this project.

**Comment by jochenw** [comment]
Not sure about that. At least, this used to be offered by the original Sysdeo plugin. See, for example,
https://www.torsten-horn.de/techdocs/jee-tomcat-sysdeo.htm.
