### ISSUE TITLE
Problem with Eclipse Photon 4.8

### ISSUE THREAD

**Issue by eealba** [tomcatplugin/tomcatplugin#4]
Installing version 9.1.3 in the last eclipse 4.8 does not show the Start, Stop, Restart icons. In Preferences, the Tomcat node does not appear.

There is no error in the "Log error" and in the Installation Details appears correctly.

Is this version of eclipse supported?

![image](https://user-images.githubusercontent.com/24897989/42234396-b3883aa4-7ef4-11e8-994f-2089c6f0e8fa.png)

**Comment by markuskeunecke** [comment]
This seems to be sth that repeats on every new version of eclipse. The last releases there were some changes in dependencies which lead to the problem you are facing.

I did not yet find time to test it on eclipse photon, yet.

**Comment by eealba** [comment]
Resolved, with a clean installation and a new folder .p2 the plugin is installed correctly in Photon
