### ISSUE TITLE
webClassPathEntries can't be cleared

### ISSUE THREAD

**Issue by liangyi-xu** [tomcatplugin/tomcatplugin#5]
WebClassPathEntries will not be cleared  even though Tomcat project be restarted in a DevLoader uncheck all state.

tomcatplugin v9.1.0

**Comment by markuskeunecke** [comment]
@DAC-liangyi can you please elaborate a bit more on your issue? I did not gather any experience using the DevLoader and stuff since I adopted the maintenance of the Eclipse Tomcat Plugin.

**Comment by liangyi-xu** [comment]
My description is too simple,sorry.

Steps to reproduce the problem as follows:

1.Tomcat project -> properties->Tomcat->DevLoader classpath
  a.Activate devloader checkon
  b.checkon more than one webClassPathEntry
2.Start tomcat by tomcat plugin
3.And than,the file named of .#webclasspath will be created automatically.
  The content of the .#webclasspath file is the list of webClassPathEntries which has been selected by me.
4.Stop the tomcat.
5.Tomcat project -> properties->Tomcat->DevLoader classpath
  a.Keep Activate devloader checkon
  b.Make all the webClassPathEntries unchecked
6.Restart tomcat by tomcat plugin 
  And than the content of .#webclasspath file is the same as the first time.

Previously,I used tomcat plugin v331,when I done the steps as described above,.#webclasspath was going to be cleared.

**Comment by markuskeunecke** [comment]
Okay, thank you for your detailed description. I will have a try on reproducing the issue.

**Comment by markuskeunecke** [comment]
Seems you have found a long existing bug. I fixed it by always deleting the file on tomcat start. The fix will go live with the next release.

**Comment by markuskeunecke** [comment]
Release has been pushed to update site.

**Comment by liangyi-xu** [comment]
Thank you for your modification.
I verified version V9.1.2. And the problem has been resolved.
