### ISSUE TITLE
How can I load java projects when start tomcat by tomcat plugin

### ISSUE THREAD

**Issue by liangyi-xu** [tomcatplugin/tomcatplugin#6]
There is only one tomcat project and any java projects in my workspace.
The java projects has class file but not builded to jar.When I start tomcat by tomcat plugin,
how can I load the java projects?

**Comment by markuskeunecke** [comment]
It is not clear to me, what you are aiming at, @DAC-liangyi. Should the Java Projects be treated as separate webapps? Should they be integrated as part of you the webapp contained in the single Tomcat project?
